# docker-compose.debug.yml
version: "3.9"

services:
  db:
    image: postgres:11
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks_db

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - "sh"
      - "-c"
      - |
        pip install debugpy -t /tmp \
        && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 \
        -m alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8085        
    ports:
      - 8085:8085
      - 5678:5678
    depends_on:
      - db